# name: test1
# #
# on:
#   push:
#   pull_request:

# jobs:
#   Test_build_and_server:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Download repo and set as the current directory
#         uses: actions/checkout@v4

#       - name: Setup python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.11"
        
#       - name: Install python dependencies
#         run: pip install -r requirements.txt

#       - name: Build docka image
#         run: docker build -t taskmanagerimage .

#       - name: Run the container
#         run: docker run -d -p 5000:5000 taskmanagerimage

#       - name: Wait for the server to start
#         run: |
#           for i in {1..20}; do
#             if curl -s http://localhost:5000 >/dev/null; then
#               echo "Server is UP!"
#               exit 0
#             fi
#             echo "Waiting for server..."
#             sleep 1
#           done

#       - name: run_the_hello_client
#         run: python tests/hello_client.py